'use client';
import {useEffect,useRef,useState} from 'react';
import {Copy,ChevronDown} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import Background from './scene';
import Intro from './intro';
import Portfolio from './portfolio';
type Profile={name:string;bio:string;avatar:string};
const fallback:Profile={name:'Nior',bio:'',avatar:'/profile.jpg'};
export default function Experience(){
 const [profile,setProfile]=useState(fallback),[owner,setOwner]=useState(false),[quiet,setQuiet]=useState(false);
 const root=useRef<HTMLDivElement>(null),hero=useRef<HTMLElement>(null),contact=useRef<HTMLElement>(null);
 useEffect(()=>{let cancelled=false;fetch('/api/profile').then(r=>{if(!r.ok)throw Error();return r.json();}).then((data:unknown)=>{const f=data as {profile:Profile;owner:boolean};if(!cancelled){setProfile(f.profile);setOwner(f.owner);}}).catch(()=>{});return()=>{cancelled=true;};},[]);
 useEffect(()=>{const el=root.current,h=hero.current,c=contact.current;if(!el||!h||!c)return;let frame=0;const preference=matchMedia('(prefers-reduced-motion: reduce)');
 const draw=()=>{frame=0;const reduced=quiet||preference.matches;el.classList.toggle('journey-still',reduced);const hr=h.getBoundingClientRect(),cr=c.getBoundingClientRect();const p=reduced?0:Math.min(1,Math.max(0,-hr.top/Math.max(1,h.offsetHeight-innerHeight)));const end=reduced?1:Math.min(1,Math.max(0,(innerHeight-cr.top)/(innerHeight*.85)));el.style.setProperty('--hero-scale',String(1-p*.42));el.style.setProperty('--hero-y',`${-p*95}px`);el.style.setProperty('--hero-opacity',String(Math.max(0,1-p*1.25)));el.style.setProperty('--hero-rotate',`${p*9}deg`);el.style.setProperty('--return-scale',String(.72+end*.28));el.style.setProperty('--return-y',`${(1-end)*90}px`);el.style.setProperty('--return-opacity',String(end));el.style.setProperty('--space-scale',String(1+(p*.35)*(1-end)));};
 const schedule=()=>{if(!frame)frame=requestAnimationFrame(draw);};window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);preference.addEventListener('change',schedule);draw();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);preference.removeEventListener('change',schedule);};},[quiet]);
 return <div className="journey" ref={root}><Intro/><Background/><Toaster theme="dark" position="top-center"/>
 <a className="journey-skip" href="#work">ข้ามไปผลงาน</a>
 <header className="journey-nav"><a href="#home" className="wordmark" aria-label="กลับหน้าแรก">nior<span>®</span></a><nav aria-label="เมนูหลัก"><a href="#work">ผลงาน</a><a href="#contact">ติดต่อ</a></nav><button className="motion-toggle" aria-pressed={quiet} onClick={()=>setQuiet(v=>!v)}>{quiet?'เปิดเอฟเฟกต์':'ลดเอฟเฟกต์'}</button></header>
 <main><section id="home" ref={hero} className="journey-hero"><div className="hero-sticky"><div className="scene-coordinate coordinate-top">01 / INTRODUCTION</div><div className="hero-profile"><div className="portrait-orbits" aria-hidden="true"><i/><i/><i/></div><span className="hero-avatar photo"><img src={profile.avatar} alt={profile.name} fetchPriority="high" draggable={false}/></span><p className="hero-handle">@hypnxs_.n</p><h1>{profile.name}<span>®</span></h1>{profile.bio&&<p className="hero-bio">{profile.bio}</p>}</div><a href="#work" className="scroll-invitation"><span>เลื่อนเพื่อสำรวจ</span><ChevronDown size={18}/></a><div className="scene-coordinate coordinate-bottom">PERSONAL SPACE / OPEN TO YOU</div></div></section>
 <section id="work" className="journey-work"><Portfolio owner={owner} immersive quiet={quiet}/></section>
 <section id="contact" ref={contact} className="journey-contact"><div className="contact-sticky"><div className="contact-arrival"><p className="eyebrow">03 / BACK TO ME</p><span className="contact-avatar photo"><img src={profile.avatar} alt={profile.name} loading="lazy"/></span><h2>Let’s connect.</h2><div className="journey-contact-links"><a href="https://www.instagram.com/hypnxs_.n/" target="_blank" rel="noopener noreferrer"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.6" r="1" fill="currentColor" stroke="none"/></svg><span>Instagram<small>@hypnxs_.n</small></span></a><button onClick={async()=>{try{await navigator.clipboard.writeText('n_.hypnxs');toast.success('คัดลอกชื่อ Discord แล้ว');}catch{toast.error('ชื่อ Discord: n_.hypnxs');}}}><img src="/discord.svg" width={21} height={21} alt=""/><span>Discord<small>n_.hypnxs</small></span><Copy size={16}/></button></div><a className="contact-back" href="#home">กลับไปจุดเริ่มต้น</a></div><footer className="journey-footer"><span>© {new Date().getFullYear()} NIOR</span><a href="/studio">{owner?'จัดการเว็บไซต์':'สำหรับเจ้าของเว็บไซต์'}</a></footer></div></section></main>
 </div>;
}
